### PR TITLE
Fix jsf1-portlet edit-preferences navigation-case to have the correct file extension of '.xhtml'

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a, please merge to `2.1.x` and forward-port to `2.2.x`.

**Comment by ngriffin7a** [comment]
@stiemannkj1 is there a FACES issue associated with this? If not please create a FACES issue with a description for reproducing the problem and let me know the ticket number. No need to re-submit the PR as I can simply amend your last commit message.

**Comment by stiemannkj1** [comment]
Here's the issue: [FACES-2377](https://issues.liferay.com/browse/FACES-2377)

**Comment by ngriffin7a** [comment]
Merged in to 2.1.x and forward-ported to 2.2.x. Thank you.

**Pull request closed without merging**
