### PR TITLE
FACES-2138 no liferay-hook.xml needed for 3.0.x-legacy

### PR DESCRIPTION
**Pull request by vsingleton**

### CODE REVIEW

**Comment by juangon** [comment]
Ouch! I was doing this task. Additionally. we have to fix other things that makes showcase broken in 3.0.x-legacy. Does it work for you?

**Comment by ngriffin7a** [comment]
@juangon No worries -- @vsingleton identified the problem with liferay-hook.xml as well as another that was causing the MissingResource problem you showed me earlier today https://github.com/liferay/liferay-faces/pull/775 -- we are making it easier for you to complete the FACES-2138 task in the 3.0.x-legacy branch

**Comment by juangon** [comment]
Ok thanks mates @ngriffin7a @vsingleton . Just seen this PR https://github.com/vsingleton/liferay-faces/commit/3df7957b93d195f60939e8d1c99ca26bf62d5efb.

**Comment by ngriffin7a** [comment]
Merged in to 3.0.x-legacy. Thank you.

**Pull request closed without merging**
