### PR TITLE
FACES-2230 icefaces1-ipc-ajax-push-portlet fails to deploy

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
This should be backported to 2.1.x as well.

**Comment by ngriffin7a** [comment]
@stiemannkj1 Thanks for the pull request Kyle. Rather than adding liferay-faces-bridge-impl.jar as a dependency, please simply copy com.liferay.faces.bridge.el.internal.ELResolverImpl from liferay-faces-bridge-impl.jar to liferay-faces-bridge-ice.jar. This may not be the most modular way of doing things, but liferay-faces-bridge-ice.jar is meant to be a subset of the functionality in liferay-faces-bridge-impl.jar

**Comment by ngriffin7a** [comment]
Actually I think that the problem is that the existing class did not get migrated to the "internal" sub-package: https://github.com/liferay/liferay-faces/tree/2.2.x/bridge-ice/src/main/java/com/liferay/faces/bridge/el

**Comment by stiemannkj1** [comment]
Re-sent as #545

**Pull request closed without merging**
