### PR TITLE
FACES-2070 Rename datePattern and timePattern to pattern for consistency

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by juangon** [comment]
Merge conflicts here too @stiemannkj1

**Comment by stiemannkj1** [comment]
@juangon,
Fixed. Thanks!

**Comment by juangon** [comment]
Ooops, it still appears grey to me :-(

**Comment by stiemannkj1** [comment]
Fixed again. Thanks @juangon.

**Pull request merged**
