### PR TITLE
FACES-2362 Upgrade bridge demos to use a newer version of selenium (specify older version of firefox to run the bridge tck since it is incompatible with the current version of firefox)

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@ngriffin7a, @vsingleton, @pcwhite, @juangon,
If you want to be able to run the bridge-tck, rename the Firefox 21.0 `Firefox.app/` folder to `Firefox21.app/`.

**Comment by vsingleton** [comment]
Great pull request, Kyle!

**Comment by juangon** [comment]
:clap: :clap: :clap:

**Comment by stiemannkj1** [comment]
Re-sent as #798

**Pull request closed without merging**
