### PR TITLE
FACES-1892 Change to Unified-EL

### PR DESCRIPTION
**Pull request by juangon**
Finally I had to made some minor change in showcase-fn taglib namespace, as from EL 2.1 the dashes aren't permitted.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@juangon Is it necessary to include the GlassFish el-impl.jar as a compile-time dependency for all servers? My assumption was that Tomcat, GlassFish, JBoss, etc. all come with an EL implementation that complies with the Unified EL?

**Comment by juangon** [comment]
Mmm what makes this different from our older jboss el 2.0 impl? I mean, if we needed this dependency then, why not adding that dependency now?

**Comment by ngriffin7a** [comment]
At the bottom of the FACES-1892 description: "However, since Java EE 6 servers are required to ship with a default implementation of the EL 2.2 API, it might be possible to completely eliminate the pom.xml dependency and web.xml context-param described above. This is the approach that should be tried first."

**Comment by juangon** [comment]
Re-sent here: https://github.com/liferay/liferay-faces/pull/538

**Pull request closed without merging**
