### PR TITLE
FACES-1723 Enable pluto maven profile to login to pluto and test the bridge demos (turn off unused tests in pluto, and fix issues/bridge tests for pluto)

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
Merged in to master (4.2.x) and backported to all branches as appropriate. Thank you.

**Comment by ngriffin7a** [comment]
@stiemannkj1 please review the backport to 3.0.x-legacy because there were some merge conflicts and I simply accepted the changes from the pull request.

**Comment by ngriffin7a** [comment]
@stiemannkj1 3.0.x-legacy commit https://github.com/liferay/liferay-faces/commit/7e4bffb79023d8fe3ab5039710fa23c8fc01f2c2

**Comment by stiemannkj1** [comment]
@ngriffin7a, done: #882

**Comment by stiemannkj1** [comment]
@ngriffin7a, actually everything is working in `3.0.x` but I did find a bug in all branches related to the path. I fixed it here: #883

**Pull request merged**
