### PR TITLE
FACES-2324 remove StringPool.java

### PR DESCRIPTION
**Pull request by pcwhite**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@pcwhite, this commit seems to have merge conflicts. I think you need to rebase your branch.

**Comment by ngriffin7a** [comment]
@stiemannkj1 are you referring to a couple of classes, one of which is TabHandler.java?

**Comment by ngriffin7a** [comment]
@stiemannkj1 I think I resolved the merge conflicts with a code review commit 4575c7d413654c1de914d326d79d4bb32f8cffca

**Comment by ngriffin7a** [comment]
Merged in to master (4.2.x) and backported to all branches. Thank you.

**Pull request closed without merging**
