### PR TITLE
Append "" instead of "null" when null is appended to StringBuilder.

### PR DESCRIPTION
**Pull request by patrikbergstrom**
Hi,

Thanks Neil for your reply on my previous pull request (https://github.com/liferay/liferay-faces/pull/462) and thanks for pointing me in the right direction. I hope I got everything right this time.

I guess this applies to all branches. It was in the 3.2.x branch I discovered the problem.

https://issues.liferay.com/browse/FACES-2180

Best regards,
Patrik

### CODE REVIEW

**Comment by ngriffin7a** [comment]
Hi Patrik, thanks again for the pull request. When you get a chance, please click on the "Contribute Solution" button on the FACES-2180 issue. Thanks, Neil

**Comment by patrikbergstrom** [comment]
Hi Neil,

Maybe you have seen already but if not I have made the "Contribute Solution" now.

Cheers,
Patrik

**Comment by ngriffin7a** [comment]
@patrikbergstrom Thanks Patrik -- I merged your commit and then made a small change with an additional commit on top of it. When you get a chance, please let me know if it works in your environment. Kind Regards, Neil

**Comment by patrikbergstrom** [comment]
Looks good. I just ran with your latest changes and it works fine on my server.

Best Regards,
Patrik

**Comment by ngriffin7a** [comment]
Thanks for letting us know, and thanks again for submitting the bug and pull request :)

**Comment by patrikbergstrom** [comment]
Thanks, I'm happy to contribute. Maybe you'll hear from me again later on :)

**Pull request closed without merging**
